
@url_base = http://localhost:5000/api
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGVkcm8gQWx2ZXMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImV4cCI6MTc1MDQ3MTUwMCwiaXNzIjoiUmVzZXJ2YVNhbGFzQVBJIiwiYXVkIjoiVXN1YXJpb0FQSSJ9.xke38kf5MQluQavBYevPSq3pLh6T-8w9Sm2oYtHfGFY
@userToken = 

### 1. Listar logs de AUDITORIA para RESERVAS CRIADAS
# Este endpoint chama o método ListarReservasCriadas() no seu AuditoriaController.
GET {{url_base}}/auditoria/reservas/criadas
Authorization: Bearer {{adminToken}}


### 2. Listar logs de AUDITORIA para RESERVAS EXCLUÍDAS
# Este endpoint chama o método ListarReservasExcluidas() no seu AuditoriaController.
GET {{url_base}}/auditoria/reservas/excluidas
Authorization: Bearer {{adminToken}}