@url_base = http://localhost:5000/api 

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdGUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMTciLCJleHAiOjE3NDcwMjU2MjgsImlzcyI6IlJlc2VydmFTYWxhc0FQSSIsImF1ZCI6IlVzdWFyaW9BUEkifQ.M5ZSedCA04pk1eIrOxqXK9lxd_njYKtilivHjaG0Gqs
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdGUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoieXVyaTExQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNiIsImV4cCI6MTc0NzAyMzM1NiwiaXNzIjoiUmVzZXJ2YVNhbGFzQVBJIiwiYXVkIjoiVXN1YXJpb0FQSSJ9.UfPy2qRZEeVnZc9Oxz_7oJIBUn35IiTNY2xBYuMgIr8
### 1. Criar uma nova reserva (usuário comum)
POST {{url_base}}/reserva
Authorization: Bearer {{userToken}}
Content-Type: application/json 

{
    "salaId": 6,
    "dataHoraInicio": "2025-07-15T16:00:00", 
    "dataHoraFim": "2025-07-16T17:00:00"
}

### 2. Listar MINHAS reservas (usuário comum)
GET {{url_base}}/reserva/minhas
Authorization: Bearer {{userToken}}

### 3. Listar TODAS as reservas (admin)
GET {{url_base}}/reserva
Authorization: Bearer {{adminToken}}

###
DELETE {{url_base}}/reserva/remover/1
Authorization: Bearer {{adminToken}}