@url_base = http://localhost:5000/api 

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGVkcm8gQWx2ZXMyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJleHAiOjE3NTA4MTcwNDQsImlzcyI6IlJlc2VydmFTYWxhc0FQSSIsImF1ZCI6IlVzdWFyaW9BUEkifQ.YlIQIuCAVkPwTF3OEHyiYK66J0c3V-SxjLMX5gM6VeE
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiUGVkcm8gQWx2ZXMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoidXNlckBlbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJleHAiOjE3NTA0NzE4NTYsImlzcyI6IlJlc2VydmFTYWxhc0FQSSIsImF1ZCI6IlVzdWFyaW9BUEkifQ.1dnM8HwZ4FkUiS9oXcDfgCcPvzb08E2eZPVjgjlX7X4
### 1. Criar uma nova reserva (usuário comum)
POST {{url_base}}/reserva
Authorization: Bearer {{userToken}}
Content-Type: application/json 

{
    "salaId": 3,
    "dataHoraInicio": "2025-07-15T16:00:00", 
    "dataHoraFim": "2025-07-16T17:00:00"
}

### 2. Listar MINHAS reservas (usuário comum)
GET {{url_base}}/reserva/minhas
Authorization: Bearer {{userToken}}

### 3. Listar TODAS as reservas (admin)
GET {{url_base}}/reserva
Authorization: Bearer {{adminToken}}

###
DELETE {{url_base}}/reserva/remover/1
Authorization: Bearer {{adminToken}}