@url_base = http://localhost:5000/api

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdGUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMSIsImV4cCI6MTc1MDE3MDg4NiwiaXNzIjoiUmVzZXJ2YVNhbGFzQVBJIiwiYXVkIjoiVXN1YXJpb0FQSSJ9.Nu3WgNIFP9HcUZl7m1eUu79syJUknRzOZHAtGJ-SWMw

### 1. Listar salas (SEM TOKEN - Público)
GET {{url_base}}/salas/listar

### 2. Criar sala (EXIGE TOKEN ADMIN)
POST {{url_base}}/salas/registrar
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "Nome": "Sala Normal 6",
    "Capacidade": 11
}
    
### EDITAR SALA
PUT {{url_base}}/salas/editar/3
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "Nome": "Sala Normal 7",
    "Capacidade": 50
}

### BUSCAR SALA
GET {{url_base}}/salas/3
Authorization: Bearer {{adminToken}}

### 3. Deletar sala (EXIGE TOKEN ADMIN)
DELETE {{url_base}}/salas/remover/2
Authorization: Bearer {{adminToken}}
