@url_base = http://localhost:5000/api

### 1. Listar salas (SEM TOKEN - Público)
GET {{url_base}}/salas/listar

### 2. Criar sala (EXIGE TOKEN ADMIN)
POST {{url_base}}/salas/registrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4xIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbjFAZW1haWwuY29tIiwiZXhwIjoxNzQ2OTI3Njc4LCJpc3MiOiJSZXNlcnZhU2FsYXNBUEkiLCJhdWQiOiJVc3VhcmlvQVBJIn0.cz-33xpdbb3SGdULjvtWc8hijC8_YCibkVOQmlvp3Lo
Content-Type: application/json

{
    "Nome": "Sala Normal 6",
    "Capacidade": 12
}

### 3. Deletar sala (EXIGE TOKEN ADMIN)
DELETE {{url_base}}/salas/remover/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4xIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbjFAZW1haWwuY29tIiwiZXhwIjoxNzQ2OTI3Njc4LCJpc3MiOiJSZXNlcnZhU2FsYXNBUEkiLCJhdWQiOiJVc3VhcmlvQVBJIn0.cz-33xpdbb3SGdULjvtWc8hijC8_YCibkVOQmlvp3Lo
### EDITAR SALA
PUT {{url_base}}/salas/editar/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4xIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbjFAZW1haWwuY29tIiwiZXhwIjoxNzQ2OTI3Njc4LCJpc3MiOiJSZXNlcnZhU2FsYXNBUEkiLCJhdWQiOiJVc3VhcmlvQVBJIn0.cz-33xpdbb3SGdULjvtWc8hijC8_YCibkVOQmlvp3Lo
Content-Type: application/json

{
    "Nome": "Sala Normal 22",
    "Capacidade": 50
}

### BUSCAR SALA
GET {{url_base}}/salas/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4xIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbjFAZW1haWwuY29tIiwiZXhwIjoxNzQ2OTI3Njc4LCJpc3MiOiJSZXNlcnZhU2FsYXNBUEkiLCJhdWQiOiJVc3VhcmlvQVBJIn0.cz-33xpdbb3SGdULjvtWc8hijC8_YCibkVOQmlvp3Lo
