@url_base = http://localhost:5000/api

### 1. Listar salas (SEM TOKEN - Público)
GET {{url_base}}/salas/listar

### 2. Criar sala (EXIGE TOKEN ADMIN)
POST {{url_base}}/salas/registrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQGVtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMyIsImV4cCI6MTc0NzAwNzQ1MSwiaXNzIjoiUmVzZXJ2YVNhbGFzQVBJIiwiYXVkIjoiVXN1YXJpb0FQSSJ9.UDUgmhJ_I_zTySUSlrKLkG4o_3uxPMbNFSj694ikrpE
Content-Type: application/json

{
    "Nome": "Sala Normal 117",
    "Capacidade": 12
}

### 3. Deletar sala (EXIGE TOKEN ADMIN)
DELETE {{url_base}}/salas/remover/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXN1YXJpbzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6IjEyM0BlbWFpbC5jb20iLCJleHAiOjE3NDcwMDEwMzEsImlzcyI6IlJlc2VydmFTYWxhc0FQSSIsImF1ZCI6IlVzdWFyaW9BUEkifQ.abYR_C2U36Ow7FS0Ph81Ikcqi7NIiC-flrSjmoOFZdk
### EDITAR SALA
PUT {{url_base}}/salas/editar/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXN1YXJpbzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzdWFyaW9AZW1haWwuY29tIiwiZXhwIjoxNzQ2OTk3NjY4LCJpc3MiOiJSZXNlcnZhU2FsYXNBUEkiLCJhdWQiOiJVc3VhcmlvQVBJIn0.o6Ry4gPaW987C9_1EtB0RIIP3NIAJKQ8xIvdr5vRH0w
Content-Type: application/json

{
    "Nome": "Sala Normal 22",
    "Capacidade": 50
}

### BUSCAR SALA
GET {{url_base}}/salas/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVXN1YXJpbzEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InVzdWFyaW9AZW1haWwuY29tIiwiZXhwIjoxNzQ2OTk3NjY4LCJpc3MiOiJSZXNlcnZhU2FsYXNBUEkiLCJhdWQiOiJVc3VhcmlvQVBJIn0.o6Ry4gPaW987C9_1EtB0RIIP3NIAJKQ8xIvdr5vRH0w
